title: 'rezalaal.tb::lang.tables.years.title'
modelClass: Rezalaal\Tb\Models\Years
list: $/rezalaal/tb/models/years/columns.yaml
recordUrl: 'rezalaal/tb/years/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
