title: 'rezalaal.tb::lang.tables.emptypes.title'
modelClass: Rezalaal\Tb\Models\EmpTypes
list: $/rezalaal/tb/models/emptypes/columns.yaml
recordUrl: 'rezalaal/tb/emptypes/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
