name: 'rezalaal.tb::lang.tables.emptypes.title'
modelClass: Rezalaal\Tb\Models\EmpTypes
form: $/rezalaal/tb/models/emptypes/fields.yaml
defaultRedirect: rezalaal/tb/emptypes
create:
    title: 'backend::lang.form.create'
    redirect: 'rezalaal/tb/emptypes/update/:id'
    redirectClose: rezalaal/tb/emptypes
update:
    title: 'backend::lang.relation.update'
    redirect: rezalaal/tb/emptypes
    redirectClose: rezalaal/tb/emptypes
preview:
    title: 'backend::lang.form.preview'
