name: 'rezalaal.tb::lang.tables.weekly_contracts.title'
modelClass: Rezalaal\Tb\Models\WeeklyContract
form: $/rezalaal/tb/models/weeklycontract/fields.yaml
defaultRedirect: rezalaal/tb/weeklycontract
create:
    title: 'backend::lang.form.create'
    redirect: 'rezalaal/tb/weeklycontract/update/:id'
    redirectClose: rezalaal/tb/weeklycontract
update:
    title: 'backend::lang.relation.update'
    redirect: rezalaal/tb/weeklycontract
    redirectClose: rezalaal/tb/weeklycontract
preview:
    title: 'backend::lang.form.preview'
