title: 'rezalaal.tb::lang.tables.monthly_performances.title'
modelClass: Rezalaal\Tb\Models\MonthlyPerformances
list: $/rezalaal/tb/models/monthlyperformances/columns.yaml
recordUrl: 'rezalaal/tb/monthlyperformances/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
filter: config_filter.yaml
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
